<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Kingdom
 *
 * @ORM\Table(name="kingdom")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\KingdomRepository")
 */
class Kingdom
{
    /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Person", mappedBy="kingdom")
     */
    private $persons;

    /**
     * @return mixed
     */
    public function getPersons()
    {
        return $this->persons;
    }

    /**
     * @param mixed $persons
     * @return Kingdom
     */
    public function setPersons($persons)
    {
        $this->persons = $persons;

        return $this;
    }

    public function __toString()
    {
        return $this->id . ' - ' . $this->name. ' - ' . $this->capital;
    }

    /* Autogenerated methods / variables */

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="capital", type="string", length=255)
     */
    private $capital;

    /**
     * @var int
     *
     * @ORM\Column(name="nb_inhabitant", type="integer")
     */
    private $nbInhabitant;

    /**
     * @return int
     */
    public function getNbInhabitant()
    {
        return $this->nbInhabitant;
    }

    /**
     * @param int $nbInhabitant
     */
    public function setNbInhabitant($nbInhabitant)
    {
        $this->nbInhabitant = $nbInhabitant;
    }


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Kingdom
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set capital
     *
     * @param string $capital
     *
     * @return Kingdom
     */
    public function setCapital($capital)
    {
        $this->capital = $capital;

        return $this;
    }

    /**
     * Get capital
     *
     * @return string
     */
    public function getCapital()
    {
        return $this->capital;
    }


}

